### PR TITLE
Added minor support for multi_get

### PR DESCRIPTION
**Pull request by hhoundem**
Just added a simple multi get (where only ids are specified). i.e.

curl 'localhost:9200/test/type/_mget' -d '{
    "ids" : ["1", "2"]
}'

No test cases, although I could knock a simple one out if you want.

### CODE REVIEW

**Comment by grantr** [comment]
Simple test would be nice! Doesn't have to cover corner cases, just an 'it works' test.

Also could you squash these commits together?

Thanks!

**Comment by hhoundem** [comment]
Cool. Added a minor test inside of the index_spec and squashed em.

**Comment by hhoundem** [comment]
Also, for now it simply returns everything as elastic search does, meaning:

{"docs":[{...}, {...}]}

Not sure if you want that, or for it to pull out the object array.

**Comment by grantr** [comment]
Since get returns a Hit object, multi_get should probably return an array of Hit objects also. The Hits class should not be used, since it's more for query results.

I'm regretting baking the Hit(s) stuff into the api at the lowest level, but can't change it now without major breakage. If I could do it over again I'd make rubberband strictly lower level and write another gem on top that adds niceties.

**Comment by hhoundem** [comment]
Alright, returns an array of Hit objects now.

**Comment by grantr** [comment]
Thanks! Released in 0.1.2

**Pull request merged**
