### PR TITLE
Had to namespace encoder for ruby 1.9

### PR DESCRIPTION
**Pull request by makrisoft**
try it out in 1.8 before you merge this finally.

Thanks
Ernie

### CODE REVIEW

**Comment by grantr** [comment]
Did you mean to commit the change in set_encoding! as well?

**Comment by grantr** [comment]
never mind, it's removed in the merge

**Comment by makrisoft** [comment]
Hi,

originally yeah, but I saw that it was fixed this morning. I may start some tests too, can you take those as they come?

**Comment by grantr** [comment]
definitely, i've been meaning to write tests too but haven't had the time. It would be awesome if you wrote some!

**Pull request merged**
