### PR TITLE
Bulk index and delete support for parent and routing options

### PR DESCRIPTION
**Pull request by jkebinger**
Hello, I ran into a problem testing out the parent/child support in elastic search because bulk index operations weren't hoisting _parent out of the document into the index command. The commit here adds support for that.

### CODE REVIEW

**Comment by grantr** [comment]
Looks good, but can you explain why you chose to implement it this way instead of just merging options like @fotonauts did? fotonauts/rubberband@73eed29c4e963889a8d3b111e4e5aba706b9de15

The merge seems like a cleaner solution if it works.

**Comment by jkebinger** [comment]
I enabled the parent and routing parameters to be captured from the document or the options hash on the basis of least surprise for users coming from the simple (non-bulk) index command, which does understand _parent and _routing in the document itself. I could be wrong on both of those counts, and so it would make sense to simply merge options in.

**Comment by grantr** [comment]
rubberband does not currently do anything special to support routing and parent keys in documents (rather than options), so if that is possible it is provided by elasticsearch. I can't find anywhere in the es docs that mentions that _routing and _parent are accepted in the document when indexing, so if that support exists it could be a bug and may be removed in the future.

In any case, I think rubberband should have as little magic as possible so I am going to go with a simple merge. Thanks anyway for the pull request!

PS If you can prove that rubberband IS pulling _parent and _routing out of documents, create a separate issue because that is certainly a bug :)

**Comment by grantr** [comment]
This functionality has been released in version 0.1.0

**Pull request closed without merging**
